controller.B.onEvent(ControllerButtonEvent.Pressed, function () {
    game.splash(invatory)
})
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    if (true) {
        game.splash(invatory)
        invatory.push("kettle")
    } else if (mySprite.tileKindAt(TileDirection.Top, assets.tile`transparency16`)) {
        tiles.setTileAt(tiles.getTileLocation(11, 25), assets.tile`transparency16`)
    } else {
    	
    }
})
function start_game () {
    tiles.setCurrentTilemap(tilemap`level1`)
    mySprite = sprites.create(img`
        ........................
        ....ffffff..............
        ..ffeeeef2f.............
        .ffeeeef222f............
        .feeeffeeeef...cc.......
        .ffffee2222ef.cdc.......
        .fe222ffffe2fcddc.......
        fffffffeeeffcddc........
        ffe44ebf44ecddc.........
        fee4d41fddecdc..........
        .feee4dddedccc..........
        ..ffee44e4dde...........
        ...f222244ee............
        ...f2222e2f.............
        ...f444455f.............
        ....ffffff..............
        .....fff................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `, SpriteKind.Player)
    controller.moveSprite(mySprite)
    tiles.placeOnTile(mySprite, tiles.getTileLocation(8, 16))
    scene.cameraFollowSprite(mySprite)
    invatory = []
}
let mySprite: Sprite = null
let invatory: string[] = []
start_game()
