controller.B.onEvent(ControllerButtonEvent.Pressed, function () {
    game.splash(invatory)
})
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    if (true) {
        game.splash("you have a kettle")
        invatory.push("kettle")
    } else if (mySprite.tileKindAt(TileDirection.Top, sprites.dungeon.chestClosed)) {
        tiles.setTileAt(tiles.getTileLocation(11, 25), sprites.dungeon.chestOpen)
    } else {
    	
    }
})
let invatory: string[] = []
let mySprite: Sprite = null
tiles.setCurrentTilemap(tilemap`level1`)
mySprite = sprites.create(img`
    ........................
    ....ffffff..............
    ..ffeeeef2f.............
    .ffeeeef222f............
    .feeeffeeeef...cc.......
    .ffffee2222ef.cdc.......
    .fe222ffffe2fcddc.......
    fffffffeeeffcddc........
    ffe44ebf44ecddc.........
    fee4d41fddecdc..........
    .feee4dddedccc..........
    ..ffee44e4dde...........
    ...f222244ee............
    ...f2222e2f.............
    ...f444455f.............
    ....ffffff..............
    .....fff................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Player)
controller.moveSprite(mySprite)
tiles.placeOnTile(mySprite, tiles.getTileLocation(8, 16))
scene.cameraFollowSprite(mySprite)
invatory = []
